redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  minReplicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.test.com

certificate:
  enabled: true

server:
  minReplicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
